# Generated by Django 5.1.2 on 2024-11-26 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'listado_publicaciones_departamentomunicipal',
            },
        ),
        migrations.CreateModel(
            name='JuntaVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(max_length=60)),
                ('numero_calle', models.IntegerField()),
                ('departamento', models.CharField(blank=True, max_length=40, null=True)),
                ('villa', models.CharField(blank=True, max_length=40, null=True)),
                ('comuna', models.CharField(blank=True, max_length=40, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'listado_publicaciones_juntavecinal',
            },
        ),
        migrations.CreateModel(
            name='SituacionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'listado_publicaciones_situacionpublicacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('numero_telefonico_movil', models.CharField(blank=True, max_length=9, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('es_administrador', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('esta_activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'listado_publicaciones_usuario',
            },
        ),
        migrations.CreateModel(
            name='AnuncioMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listado_publicaciones_anunciomunicipal',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.departamentomunicipal')),
            ],
            options={
                'db_table': 'listado_publicaciones_categoria',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.departamentomunicipal')),
                ('junta_vecinal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.juntavecinal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('situacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.situacionpublicacion')),
            ],
            options={
                'db_table': 'listado_publicaciones_publicacion',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('extension', models.CharField(max_length=30)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.publicacion')),
            ],
            options={
                'db_table': 'listado_publicaciones_evidencia',
            },
        ),
        migrations.CreateModel(
            name='RespuestaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('acciones', models.CharField(max_length=400)),
                ('situacion_inicial', models.CharField(max_length=100)),
                ('situacion_posterior', models.CharField(max_length=100)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listado_publicaciones_respuestamunicipal',
            },
        ),
    ]
